name: Run Python Script

on:
  push:
    branches:
      - main  # 'main' branch'e push olduğunda çalışır

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu çek
        uses: actions/checkout@v4

      - name: Python ortamını kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Bağımlılıkları yükle
        run: |
          pip install -r requirements.txt

      - name: Scripti çalıştır
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          python your_script.py